[info]
bio = """
Open source enthusiast, Kotlin evangelist, Vim extraordinaire.
"""
email = "chronobserver@disroot.org"
homepage = "https://observeroftime.github.io"
name = "ObserverOfTime"
resume = "https://github.com/ObserverOfTime/resume/releases/latest/download/Resume-EN.pdf"

[links.social]
# https://www.facebook.com/{facebook}
facebook = ""
# https://www.linkedin.com/in/{linkedin}
linkedin = "chronobserver"
# https://reddit.com/user/{reddit}
reddit = "ObserverOfTime"
# https://trello.com/{trello}
trello = "chronobserver"
# https://www.tumblr.com/blog/{tumblr}
tumblr = ""
# https://www.twitch.tv/{twitch}
twitch = ""
# https://twitter.com/{twitter}
twitter = ""
# https://www.youtube.com/user/{youtube}
youtube = ""

[links.social.mastodon]
# https://{server}/@{username}
username = "chronobserver"
server = "uwu.social"

[links.vcs]
# https://gitlab.archlinux.org/{arch}
arch = "observeroftime"
# https://bitbucket.org/{bitbucket}
bitbucket = ""
# https://codeberg.org/{codeberg}
codeberg = ""
# https://gitlab.collabora.org/{collabora}
collabora = ""
# https://hub.darcs.net/{darcs}
darcs = ""
# https://salsa.debian.org/{debian}
debian = ""
# https://git.disroot.org/{disroot}
disroot = "chronobserver"
# https://fem.mint.lgbt/{femgit}
femgit = ""
# https://framagit.org/{framagit}
framagit = "ObserverOfTime"
# https://gitlab.freedesktop.org/{freedesktop}
freedesktop = ""
# https://git.fosscommunity.in/{fsci}
fsci = ""
# https://gitdab.com/{gitdab}
gitdab = ""
# https://gitea.com/{gitea}
gitea = ""
# https://gitgud.io/{gitgud}
gitgud = ""
# https://github.com/{github}
github = "ObserverOfTime"
# https://gitlab.com/{gitlab}
gitlab = "ObserverOfTime"
# https://git.rip/{gitrip}
gitrip = ""
# https://gitlab.gnome.org/{gnome}
gnome = ""
# https://invent.kde.org/{kde}
kde = ""
# https://notabug.org/{notabug}
notabug = ""
# https://sourceforge.net/users/{sourceforge}
sourceforge = ""
# https://sr.ht/~{sourcehut}
sourcehut = ""

[links.packages]
# https://aur.archlinux.org/packages/?SeB=M&K={aur}
aur = "ObserverOfTime"
# https://copr.fedorainfracloud.org/coprs/{copr}
copr = "observeroftime"
# https://metacpan.org/author/{cpan}
cpan = ""
# https://crates.io/users/{crates}
crates = ""
# https://ctan.org/home/{ctan}
ctan = ""
# https://hub.docker.com/publishers/{docker}
docker = ""
# https://github.com/{gpr}?tab=packages
gpr = ""
# https://launchpad.net/~{launchpad}
launchpad = "chronobserver"
# https://www.npmjs.com/~{npmjs}
npmjs = ""
# https://www.nuget.org/profiles/{nuget}
nuget = ""
# https://build.opensuse.org/users/{obs}
obs = ""
# https://pypi.org/user/{pypi}
pypi = "ObserverOfTime"
# https://rubygems.org/profiles/{rubygems}
rubygems = ""

[[repos.source]]
name = "yaenv"
description = "Yet another dotenv parser for Python."
tags = ["python", "django", "library"]

[[repos.source]]
name = "mpv-scripts"
description = "My personal mpv scripts."
tags = ["lua", "mpv"]

[[repos.source]]
name = "resume"
description = "Reusable resume made with RelaxedJS."
tags = ["pug", "scss", "template"]

[[repos.source]]
name = "portfolio"
description = "Reusable portfolio website made with Svelte."
tags = ["svelte", "javascript", "template"]

[[repos.source]]
name = "7SegmentDisplays"
description = "What's the longest word you can write with seven-segment displays?"
tags = ["multilanguage"]

[[repos.source]]
name = "nvimcord"
description = "A Discord Rich Presence plugin for Neovim written in Lua."
tags = ["lua", "vim", "plugin"]

[[repos.source]]
name = "tree-sitter-gitattributes"
description = "gitattributes grammar for tree-sitter."
tags = ["tree-sitter", "javascript", "library"]

[[repos.source]]
name = "tree-sitter-pymanifest"
description = "PyPA manifest grammar for tree-sitter."
tags = ["tree-sitter", "javascript", "python", "library"]

[[repos.source]]
name = "tree-sitter-chatito"
description = "Chatito grammar for tree-sitter."
tags = ["tree-sitter", "javascript", "library"]

[[repos.source]]
name = "tree-sitter-pem"
description = "PEM file grammar for tree-sitter."
tags = ["tree-sitter", "javascript", "library"]

[[repos.source]]
name = "tree-sitter-poe-filter"
description = "PoE item filter grammar for tree-sitter."
tags = ["tree-sitter", "javascript", "library"]

[[repos.source]]
name = "poe-discord-rpc"
description = "Path of Exile Discord RPC."
tags = ["typescript", "deno", "cli", "discord"]

[[repos.source]]
name = "multiedit.vim"
description = "Like :tabedit but with multiple arguments."
tags = ["vim", "plugin"]

[[repos.source]]
name = "enumagic.py"
description = "Python enums infused with magic."
tags = ["python", "library"]

[[repos.source]]
name = "DiscordThemes"
description = "A collection of my custom Discord themes."
tags = ["css", "theme", "discord"]

[[repos.source]]
name = "home.files"
description = "My dotfiles."
tags = ["config", "dotfiles", "mpv", "arch"]

[[repos.source]]
name = "dotnvim"
description = "My Neovim configuration."
tags = ["config", "dotfiles", "vim", "lua"]

[[repos.source]]
name = "PKGBUILDS"
url = "https://git.disroot.org/PKGBUILDS"
description = "A collection of my personal PKGBUILD files for Arch."
tags = ["arch"]

[[repos.source]]
name = "discord-custom-rpc"
url = "https://git.disroot.org/chronobserver/discord-custom-rpc"
description = "Simple program for creating a custom Discord RPC on Linux."
tags = ["c", "cli", "discord"]

[[repos.source]]
name = "observeroftime.github.io"
description = "My GitHub page."
tags = ["pug", "scss", "site"]

[[repos.fork]]
name = "discord.nvim"
source = "https://github.com/aurieh/discord.nvim"
description = "Discord Rich Presence for Neovim."
tags = ["vim", "python", "plugin", "discord"]

[[repos.fork]]
name = "nvim-snippy"
source = "https://github.com/mg979/nvim-snippy"
description = " Snippet plugin for Neovim."
tags = ["vim", "lua", "plugin"]

[[repos.organisation]]
name = "nvim-treesitter/nvim-treesitter"
description = "Nvim Treesitter configurations and abstraction layer."
tags = ["vim", "lua", "plugin"]

[[repos.organisation]]
name = "nvim-treesitter/nvim-treesitter-textobjects"
description = "Syntax aware text-objects, select, move, swap, and peek support."
tags = ["vim", "lua", "plugin"]

[[repos.organisation]]
name = "mangadventure/MangAdventure"
description = "A simple manga hosting CMS written in Django."
tags = ["python", "django", "scss", "javascript", "site", "manga"]

[[repos.organisation]]
name = "mangadventure/discord-webhook"
description = "Discord webhook action."
tags = ["bash", "cli", "discord"]

[[repos.organisation]]
name = "mangadventure/paperback-extensions"
description = "MangAdventure extensions for Paperback-iOS."
tags = ["typescript", "ios", "plugin", "manga"]

[[repos.organisation]]
name = "mangadventure/font"
description = "Icon font used in MangAdventure."
tags = ["webfont"]

[[repos.organisation]]
name = "TodokanaiTL/WA2EnglishPatch"
description = "White Album 2 English patch installer."
tags = ["inno", "installer", "gui", "app"]

[[repos.organisation]]
name = "TodokanaiTL/todokanaitl.github.io"
description = "TodokanaiTL website."
tags = ["html", "scss", "javascript", "site"]

[[repos.organisation]]
name = "TodokanaiTL/wa2-wine"
description = "Instructions for installing and patching White Album 2 on wine."
tags = ["docs", "tutorial"]

[[repos.contribution]]
name = "bb010g/betterdiscordctl"
description = "A utility for managing BetterDiscord on Linux."
tags = ["bash", "cli", "app", "discord"]

[[repos.contribution]]
name = "tachiyomiorg/tachiyomi-extensions"
description = "Extension catalogues for the Tachiyomi app."
tags = ["kotlin", "android", "plugin", "manga"]

[[repos.contribution]]
name = "github/linguist"
description = "GitHub Language detection."
tags = ["ruby", "app", "library"]

[[repos.contribution]]
name = "github/explore"
description = "Community-curated topic and collection pages on GitHub."
tags = ["docs"]

[[repos.contribution]]
name = "github/choosealicense.com"
description = "Non-judgmental guidance on choosing a license for your open source project."
tags = ["ruby", "site"]

[[repos.contribution]]
name = "vim/vim"
description = "The ubiquitous text editor."
tags = ["vim", "tui", "app"]

[[repos.contribution]]
name = "neovim/neovim"
description = "Vim fork focused on extensibility and usability."
tags = ["vim", "tui", "app"]

[[repos.contribution]]
name = "jose-elias-alvarez/null-ls.nvim"
description = "Use Neovim as a language server to inject LSP diagnostics, code actions, and more via Lua."
tags = ["vim", "lua", "plugin"]

[[repos.contribution]]
name = "peppercarrot/webcomics"
url = "https://framagit.org/peppercarrot/webcomics/-/commits/master?author=Observer+of+Time"
description = "A free, libre and open-source webcomic."
tags = ["webcomic", "translation"]

[[repos.contribution]]
name = "pacman/pacman-contrib"
url = "https://gitlab.archlinux.org/pacman/pacman-contrib/-/commits/master?author=ObserverOfTime"
description = "Contributed scripts and tools for pacman systems."
tags = ["vim", "plugin"]

[[repos.contribution]]
name = "dense-analysis/ale"
description = "Check syntax in Vim asynchronously and fix files."
tags = ["vim", "plugin"]

[[repos.contribution]]
name = "cakebaker/scss-syntax.vim"
description = "Vim syntax file for SCSS."
tags = ["vim", "plugin"]

[[repos.contribution]]
name = "lutris/lutris"
description = "Open Source gaming platform for GNU/Linux."
tags = ["python", "gui", "app"]

[[repos.contribution]]
name = "python-poetry/poetry"
description = "Python dependency management and packaging made easy."
tags = ["python", "cli", "app"]

[[repos.contribution]]
name = "Syncplay/syncplay"
description = "Media player synchronisation over the internet."
tags = ["python", "gui", "app"]

[[repos.contribution]]
name = "SciADV-Community/maho-bot"
description = "Fun utility bot for Discord."
tags = ["python", "discord", "bot"]

[[repos.contribution]]
name = "subject-f/cubarimoe"
url = "https://github.com/subject-f/cubarimoe/commits/develop?author=ObserverOfTime"
description = "An image proxy powered by the Cubari reader."
tags = ["python", "site"]

[[repos.contribution]]
name = "hitomi-team/discord-ipc-bridge"
description = "Enable games running under wine to use Discord Rich Presence."
tags = ["c", "wine", "discord", "app"]

[[repos.contribution]]
name = "openstyles/usercss-meta"
description = "Parse usercss styles supported by the Stylus userstyle manager."
tags = ["javascript", "node", "library"]
